#!/usr/bin/env bash

# Tail a docker container's configured logfile.
# If container is not running, script will wait for container to start
# before logging in and tailing logs.

CONTAINER="$1"
[[ -z "$CONTAINER" ]] \
    && echo "No container name/ID provided. Exiting." \
    && exit 1

RUNNING="false"
echo "Waiting for container to start..."
while [[ "$RUNNING" != "true" ]]; do
    RUNNING=$( docker container inspect $CONTAINER | jq '.[0].State.Running' )
    sleep 1
done

echo "Docker container ready! Logging in."
clear
clear
docker exec -it $CONTAINER bash -c 'tail -f $S6_LOG_FILE'
