#!/usr/bin/env zsh

# Parse file changes to ensure secrets are not being committed and
# print any potential secrets to console for review if any matches found

must_be_repo; rc=$?; [[ $rc -ne 0 ]] && exit $rc;

for file in $( all_changed_files ); do
    mongo=$( egrep '(?:mongodb(\+srv)?://)(.+$)' $file )
    aws=$( egrep '(?:.*)(?:AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID)(?:\s)?[=:]?(.+$)(?:\s)?' $file )
    ssh=$( egrep 'BEGIN OPENSSH PRIVATE KEY' $file )
    gcloud=$( egrep '(?:"client_secret":\s?"?)([^"\s]+)' $file )
    matches="$mongo$aws$ssh$gcloud"

    if [[ ! -z "$matches" ]]; then
        echo "NOT LETTING YOU COMMIT CREDENTIALS!"
        echo "Offending file: $file"
        echo "Offending content: $matches"
        exit 1
    fi
done

git commit $@
