#!/usr/bin/env bash

# Generate git blame statements for a range of lines in a file

must_be_repo; rc=$?; [[ $rc -ne 0 ]] && exit $rc;

range="$1"
[[ -z $range ]] \
    && echo "No line range supplied. Exiting" \
    && exit 1

file="$2"
[[ -z $file ]] \
    && echo "No file supplied. Exiting" \
    && exit 2

git blame -w -C -C -C -L $range $file
