#!/usr/bin/env bash

# Generate git logs for a given range of lines in a given file

must_be_repo; rc=$?; [[ $rc -ne 0 ]] && exit $rc;

range="$1"
[[ -z $range ]] \
    && echo "No line range supplied. Exiting" \
    && exit 1

file="$2"
[[ -z $file ]] \
    && echo "No file supplied. Exiting" \
    && exit 2

git log -L $range:$file
