#!/usr/bin/env bash

__git_prompt_git () {
	GIT_OPTIONAL_LOCKS=0 command git "$@"
}

ref=$(__git_prompt_git symbolic-ref --quiet HEAD 2> /dev/null)
ret=$?
if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && exit 1
    ref=$(__git_prompt_git rev-parse --short HEAD 2> /dev/null) || exit 1
fi

echo ${ref#refs/heads/}
