#!/usr/bin/env bash

# Delete all branches excluding the default branch unless the
# `-all` flag is passed, in which case only the default branch remains

for ARGUMENT in "$@"; do
    case $ARGUMENT in
        -d) [[ -z $delete_flag ]] && delete_flag="-d" ;;
        -D) [[ -z $delete_flag ]] && delete_flag="-D" ;;
        *-all) curr_branch=$( default_branch )

        *)  ;;
    esac
done

[[ -z "$delete_flag" ]] && delete_flag="-d"

main_branch=$( default_branch )
[[ -z $curr_branch ]] && curr_branch=$( git branch --show-current )
git switch $main_branch

for branch in $( git --no-pager branch -l --format="%(refname:lstrip=2)" ); do
    if [[ "$branch" != "$curr_branch" && "$branch" != "$main_branch" ]]; then
        echo "deleting branch $branch"
        git branch $delete_flag $branch
    fi
done

# trim remotes that have been deleted
git fetch -apq > /dev/null 2>&1
