#!/usr/bin/env bash

# trim all branches, except for whatever this repository's default branch is

# checkout default branch
gcm
main_branch=$( default_branch )

delete_flag="$1"
[[ -z "$delete_flag" ]] && delete_flag="-d"

# delete all branches except current branch
for branch in $( git branch | awk '{ print $1 }' ); do
    if [[ "$branch" != "$main_branch" ]]; then
        echo "deleting branch $branch"
        git branch $delete_flag $branch
    fi
done

# trim remotes that have been deleted
git fetch -apq
