#!/usr/bin/env bash

# Checkout whatever this repository's default branch is

must_be_repo; rc=$?; [[ $rc -ne 0 ]] && exit $rc;

branch=$( default_branch )
[[ ! -z "$branch" ]] && git checkout $branch
