#!/usr/bin/env bash

# Locally checkout a git branch or remote based on the provided ticket number
# If no match is found, a new branch is created with the search term

stash_work() {
    [[ ! -z "$( all_changed_files )" ]] \
        && echo "STASHING WORK" \
        && git stash -a -m "temporary stashing for gj: $search"
}

search=$@
[[ -z "$search" ]] \
    && echo "Usage: gj <jira_ticket_number>" \
    && exit 1

[[ "$search" =~ ^(master|main)$ ]] \
    && echo "Master and main are not valid search terms." \
    && exit 2

git_up 2>&1

remote=$( git branch -r --format="%(refname:lstrip=3)" | egrep -i "$search" )
local_branch=$( git branch | egrep -i "$search" )

if [[ ! -z "${remote}${local_branch}" ]]; then
    stash_work
fi

if [[ ! -z "$local_branch" && -z "$remote" ]]; then
    echo "FOUND LOCAL ONLY: $local_branch"
    git checkout $local_branch
elif [[ ! -z "$remote" ]]; then
    echo "FOUND REMOTES: $remote"
    git checkout $remote
elif [[ `len $search` -gt 9 ]]; then
    # 4 char prefix + 5 numbers makes a ticket number
    # checkout a local branch with a longer branch name
    stash_work
    git checkout -b $search
else
    echo "No result found."
fi
