#!/usr/bin/env bash

[[ -z "$1" ]] \
    && echo "Description: opens hex.pm package documentation in your default browser" \
    && echo "Usage: hex [package_name]" \
    && echo \
    && exit 1

for package in $@; do
    URL="https://hexdocs.pm/$package"
    echo "opening $URL"
    open $URL
done
