#!/usr/bin/env bash

# Kill all processes running on a given port if PID is unknown

PORT="$1"
[[ -z "$PORT" ]] \
    && echo "No port provided. Exiting" \
    && exit 1;

for pid in `getpid $PORT`; do
    killpid $pid
done
