#!/usr/bin/env bash

# Kill a process with -15 (SIGTERM) flag
# The difference between -9 (SIGKILL) and -15 (SIGTERM) is 
# SIGTERM allows the process to terminate itself
# whereas SIGKILL tells the OS to stop running the program and can cause issues.

PID="$1"
[[ -z "$PID" ]] \
    && echo "No PID provided. Exiting" \
    && exit 1;

kill -15 $PID
