#!/usr/bin/env bash

curdir=`pwd`

# summarize all git repos
for dir in $( all_git_repos ); do
    cd $dir;

    updates="$( last_week "$@" )"
    if [[ ! -z "$updates" ]]; then
        echo "[INFO] Repository: $dir"
        echo "$updates"
        echo
    fi
done

cd $curdir
