#!/usr/bin/env bash

# Generate a recap of git activity between dates for all git repos

function recap_one() {
    updates="$( recap_by_dates "$@" )"

    if [[ ! -z "$updates" ]]; then
        echo "[INFO] Repository: $dir"
        echo "$updates"
        echo
    fi
}

for dir in $( all_git_repos ); do
    (cd $dir && recap_one "$@")
done
