#!/usr/bin/env python3

# Shell-escapes JSON input for piping to other scripts, such as pretty printing

import sys

def sani(data):
    return data.replace("\"{", "{").replace("}\"", "}").replace("\\u0026", "&").replace("\\", "")

stdin = sys.stdin.read()
print(sani(stdin))
