#!/usr/bin/env bash

format='%h|%s (%cr by %ae)'

OLDEST="$1"
[[ -z "$OLDEST" ]] \
    && echo "Don't know how far back to start summarizing. Exiting" \
    && exit 1

NEWEST="$2"
[[ -z "$NEWEST" ]] && NEWEST="HEAD"

# "~" selects the nth (in this case 1 previous) commit before leftside commit sha
commit_msgs="$( git log --no-merges --format="$format" $OLDEST~1..$NEWEST )"
while IFS= read -r message; do
    # summarize each commit
    commit=$( echo $message | cut -d\| -f1 )
    tag=$( git tag --points-at $commit )
    [[ -z "$tag" ]] && tag="$commit"

    message=$( echo $message | cut -d\| -f2 )
    ticket=$( which_tix "$message" )
    url=$( tix -o "$ticket" )

    echo "$tag $url ${message/$ticket}"
done <<< "$commit_msgs"
