#!/usr/bin/env bash

[[ -z "$@" ]] \
    && echo "Description: opens a tracking ticket in the default browser" \
    && echo "Usage: t [ticket_number] [ticket_number] [ticket_number]..." \
    && echo \
    && exit 1

for ticket in $@; do
    URL="$TICKETING_URL$ticket"
    echo "opening $URL"
    open $URL
done
