#!/usr/bin/env bash

# Open tracking tickets in the default browser or just print them to console

[[ -z "$@" ]] \
    && echo "Description: opens a tracking ticket in the default browser" \
    && echo "Usage: t [-o] [ticket_number] [ticket_number] [ticket_number]..." \
    && echo \
    && exit 1

for ARGUMENT in "$@"; do
    case "$ARGUMENT" in
        -o) ONLY_ECHO=1                 ;;
        *) tickets="$tickets$ARGUMENT " ;;
    esac
done

for ticket in $tickets; do
    URL="$TICKETING_URL$ticket"
    echo "$URL"
    [[ $ONLY_ECHO -ne 1 ]] && open "$URL"
done
