#!/usr/bin/env bash

[[ "$1" == "-o" ]] && OPEN_FLAG="-o"
shift

ticket="$@"
[[ -z "$ticket" ]] && ticket=$( which_tix )

if [[ ! -z "$ticket" && "$ticket" != "TRIVIAL" && "$ticket" != "Merge" ]]; then
    t $OPEN_FLAG $ticket
else
    echo "TRIVIAL"
fi
