#!/usr/bin/env bash

[[ -z "$@" ]] \
    && echo "Description: prints a tracking ticket link" \
    && echo "Usage: to [ticket_number] [ticket_number] [ticket_number]..." \
    && echo \
    && exit 1

for ticket in $@; do
    echo "$TICKETING_URL$ticket"
done
