#!/usr/bin/env bash

# Create a new git worktree for the repo in the parent folder

must_be_repo; rc=$?; [[ $rc -ne 0 ]] && exit $rc;

TREE_NAME="$1"
[[ -z "$TREE_NAME" ]] \
    && echo "Directory name required." \
    && exit 2

COMMIT="$2"
[[ -z "$COMMIT" ]] \
    && echo "Commitish (branch/commit) required." \
    && exit 3

git worktree add $( dirname `pwd` )/$TREE_NAME $COMMIT
