#!/usr/bin/env bash

date_fmt='+%FT00:00%z'
midnight=$( date $date_fmt )
two_days_ago=$( date -v-2d $date_fmt )

# update the repository, silently
git_up > /dev/null 2>&1

# gather range of commit hashes and subjects after 2 days ago and before today
AUTHORED="$1"
if [[ "$AUTHORED" == "-a" ]]; then
    # if -a flag passed to script, only get logs I myself committed
    hashes=$( git log --no-merges --format="%H" --since=$two_days_ago --before=$midnight --committer="$( git config --get user.email )" )
else
    # otherwise, get logs committed by anyone
    hashes=$( git log --no-merges --format="%H" --since=$two_days_ago --before=$midnight )
fi

oldest_hash=$( echo "$hashes" | tail -n 1 )
newest_hash=$( echo "$hashes" | head -n 1 )

summary "$oldest_hash" "$newest_hash"